# Generated by Django 5.2.6 on 2025-09-07 18:55

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='listing',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'property', 'start_date', 'end_date')},
        ),
    ]
