# Generated by Django 5.2.6 on 2025-09-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_booking_id_booking_id_and_more'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Property',
        ),
    ]
